Migrate to hatch
nebari-dev/nebari pull request #1545
Opened 2022-11-16 14:54 UTC by iameskild

Fixes | Closes | Resolves #1510 

## Changes introduced in this PR:

- Migrate build-system to hatchling
- Move all project configs to `pyproject.toml`
  - flake8 is the one exception unfortunately - [see relevant issue](https://github.com/PyCQA/flake8/issues/234)
    - flake8 configs migrated to `.flake8` instead

## Types of changes

What types of changes does your PR introduce?

_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [x] Build related changes
- [ ] Other (please describe):

## Testing

### Requires testing

- [x] Yes
- [ ] No

### In case you checked yes, did you write tests?

- [ ] Yes
- [x] No

## Documentation

Does your contribution include breaking changes or deprecations?
If so have you updated the documentation?

- [ ] Yes, docstrings
- [ ] Yes, main documentation
- [ ] Yes, deprecation notices

## Further comments (optional)

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered and more.

2022-11-21 20:02 UTC, costrouc approved these changes

2022-11-22 13:30 UTC, trallard requested changes

2022-11-22 13:30 UTC, trallard commented on .pre-commit-config.yaml
> +      "--target-version=py310",
this can be removed

2022-11-22 13:30 UTC, trallard commented on .github/workflows/test.yaml
>            - "3.10"
As agreed need to start testing on `3.11`

2022-11-22 13:30 UTC, trallard commented on .pre-commit-config.yaml
> +      "--max-line-length=89",
let's remove this and leave all style to black

2022-11-22 14:27 UTC, trallard commented
Discussed with @iameskild  to add the creation of dev environments like we do in the hub theme

2022-11-24 06:43 UTC, ofek commented
Hatch maintainer here! Nice 🙂 FYI flake8 can now be replaced by [Ruff](https://github.com/charliermarsh/ruff):

- https://github.com/bokeh/bokeh/pull/12605
- https://github.com/zulip/zulip/pull/23431
- https://github.com/pydantic/pydantic/pull/4709
- https://twitter.com/tiangolo/status/1591912354882764802
- https://github.com/pypa/hatch/pull/607 & https://github.com/pypa/hatch/pull/608
- ...

2022-12-05 18:33 UTC, trallard commented
@iameskild  is there anything missing on your end or is this ready for a last review?

2022-12-13 12:17 UTC, costrouc approved these changes
@iameskild this looks good to me. I'm finally happy with the direction that version numbers are going instead of relying on version control.

2022-12-14 18:33 UTC, iameskild commented
@trallard this is ready for a final review. I'm not sure where the [`pre-commit.ci` ](https://results.pre-commit.ci/run/github/252841745/1671040626.PBvte5NBSSGejz3vol5hIg)came from and why its failing (the regular pre-commit GHA seems to be working as expected).

2022-12-15 15:14 UTC, trallard approved these changes
LGTM - I added a comment but it is non-blocking at all

2022-12-15 15:40 UTC, merged