Add uptime monitoring
nebari-dev/nebari pull request #2667
Opened 2024-08-30 15:01 UTC by dcmcand

## Reference Issues or PRs
part of #2557 

## What does this implement/fix?
Adds the ability to template the `kustomization.yaml` file to allow variables from the config to be dynamically set.

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [X] Did you test the pull request locally?
- [ ] Did you add new tests?

## How to test this PR?
1. enable healthchecks with
```yaml
monitoring:
  healthchecks:
    enabled: true:
```
2. run a render with `nebari render -c nebari-config.yaml`
3. check the rendered objects namespace with `grep -r  namespace stages/10-kubernetes-kuberhealthy/` and `grep -r  namespace stages/11-kubernetes-kuberhealthy-healthchecks/` and verify that the correct namespace has been set (it should be `dev`) by default.
4. change the namespace to a different namespace in your `nebari-config.yaml` file and rerun the render
5. using the above commands, verify the namespace was updated.
6. return to your original namespace and rerun the render
7. run a `nebari deploy` to validate that everything deploys to the correct namespace

## Any other comments?

2024-09-02 14:10 UTC, kcpevey commented
Reminder to add documentation for this feature - we can add a "this is in beta testing" header

2024-09-04 16:01 UTC, aktech requested changes

2024-09-05 09:59 UTC, dcmcand commented on src/_nebari/stages/base.py
> +from jinja2 import Environment, FileSystemLoader
Good catch, thanks

2024-09-05 10:02 UTC, dcmcand commented on src/_nebari/stages/kubernetes_kuberhealthy/template/kustomization.yaml.tmpl
> +  version: "{{ kuberhealthy_version }}" # v.2.7.1
It is indeed. Thanks!

2024-09-05 10:07 UTC, dcmcand commented
Thanks @aktech, I addressed all of your comments here.

2024-09-05 10:11 UTC, aktech approved these changes
Looks great to me, thanks! 🎉  This is good to merge!

2024-09-05 10:23 UTC, merged